CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250330135211_IntialCreate') THEN
    CREATE TABLE roles (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(100) NOT NULL,
        CONSTRAINT roles_pkey PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250330135211_IntialCreate') THEN
    CREATE TABLE users (
        id uuid NOT NULL,
        role_id integer NOT NULL,
        username character varying(75) NOT NULL,
        email character varying(100) NOT NULL,
        password_hash character varying(100) NOT NULL,
        created_at timestamp with time zone NOT NULL,
        status integer NOT NULL DEFAULT 0,
        last_activity timestamp with time zone,
        CONSTRAINT users_pkey PRIMARY KEY (id),
        CONSTRAINT role_id_fk FOREIGN KEY (role_id) REFERENCES roles (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250330135211_IntialCreate') THEN
    CREATE TABLE chats (
        id uuid NOT NULL,
        owner_id uuid NOT NULL,
        name character varying(100) NOT NULL,
        chat_type integer NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT chats_pkey PRIMARY KEY (id),
        CONSTRAINT owner_id_fk FOREIGN KEY (owner_id) REFERENCES users (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250330135211_IntialCreate') THEN
    CREATE TABLE user_actions (
        id uuid NOT NULL,
        user_id uuid NOT NULL,
        action text NOT NULL,
        CONSTRAINT user_actions_pkey PRIMARY KEY (id),
        CONSTRAINT "FK_user_actions_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250330135211_IntialCreate') THEN
    CREATE TABLE user_relations (
        from_user_id uuid NOT NULL,
        to_user_id uuid NOT NULL,
        relation_type integer NOT NULL,
        CONSTRAINT user_relation_pkey PRIMARY KEY (from_user_id, to_user_id),
        CONSTRAINT from_user_id_fk FOREIGN KEY (from_user_id) REFERENCES users (id),
        CONSTRAINT to_user_id_fk FOREIGN KEY (to_user_id) REFERENCES users (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250330135211_IntialCreate') THEN
    CREATE TABLE messages (
        id uuid NOT NULL,
        user_id uuid NOT NULL,
        chat_id uuid NOT NULL,
        parent_message_id uuid,
        sent_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone,
        content text NOT NULL,
        CONSTRAINT messages_pkey PRIMARY KEY (id),
        CONSTRAINT "FK_messages_messages_parent_message_id" FOREIGN KEY (parent_message_id) REFERENCES messages (id),
        CONSTRAINT "FK_messages_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id),
        CONSTRAINT chat_id_fk FOREIGN KEY (chat_id) REFERENCES chats (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250330135211_IntialCreate') THEN
    CREATE TABLE users_chats (
        chat_id uuid NOT NULL,
        user_id uuid NOT NULL,
        CONSTRAINT "PK_users_chats" PRIMARY KEY (chat_id, user_id),
        CONSTRAINT "FK_users_chats_chats_chat_id" FOREIGN KEY (chat_id) REFERENCES chats (id) ON DELETE CASCADE,
        CONSTRAINT "FK_users_chats_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250330135211_IntialCreate') THEN
    CREATE TABLE attachments (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        message_id uuid NOT NULL,
        path character varying(500) NOT NULL,
        CONSTRAINT attachments_pkey PRIMARY KEY (id),
        CONSTRAINT "FK_attachments_messages_message_id" FOREIGN KEY (message_id) REFERENCES messages (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250330135211_IntialCreate') THEN
    INSERT INTO roles (id, name)
    VALUES (1, 'User');
    INSERT INTO roles (id, name)
    VALUES (2, 'Admin');
    INSERT INTO roles (id, name)
    VALUES (3, 'SuperAdmin');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250330135211_IntialCreate') THEN
    CREATE INDEX "IX_attachments_message_id" ON attachments (message_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250330135211_IntialCreate') THEN
    CREATE INDEX "IX_chats_owner_id" ON chats (owner_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250330135211_IntialCreate') THEN
    CREATE INDEX "IX_messages_chat_id" ON messages (chat_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250330135211_IntialCreate') THEN
    CREATE UNIQUE INDEX "IX_messages_parent_message_id" ON messages (parent_message_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250330135211_IntialCreate') THEN
    CREATE INDEX "IX_messages_user_id" ON messages (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250330135211_IntialCreate') THEN
    CREATE INDEX "IX_user_actions_user_id" ON user_actions (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250330135211_IntialCreate') THEN
    CREATE INDEX "IX_user_relations_to_user_id" ON user_relations (to_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250330135211_IntialCreate') THEN
    CREATE UNIQUE INDEX "IX_users_email" ON users (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250330135211_IntialCreate') THEN
    CREATE INDEX "IX_users_role_id" ON users (role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250330135211_IntialCreate') THEN
    CREATE UNIQUE INDEX "IX_users_username" ON users (username);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250330135211_IntialCreate') THEN
    CREATE INDEX "IX_users_chats_user_id" ON users_chats (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250330135211_IntialCreate') THEN
    PERFORM setval(
        pg_get_serial_sequence('roles', 'id'),
        GREATEST(
            (SELECT MAX(id) FROM roles) + 1,
            nextval(pg_get_serial_sequence('roles', 'id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250330135211_IntialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250330135211_IntialCreate', '9.0.2');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250403112320_PasswordRecoveryAndEmailConfirmation') THEN
    ALTER TABLE users ADD email_confirmation_token character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250403112320_PasswordRecoveryAndEmailConfirmation') THEN
    ALTER TABLE users ADD password_recovery_token character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250403112320_PasswordRecoveryAndEmailConfirmation') THEN
    INSERT INTO users (id, created_at, email, email_confirmation_token, last_activity, password_hash, password_recovery_token, role_id, status, username)
    VALUES ('3d1813da-ab04-4045-97ed-e43f1c4fd51f', TIMESTAMPTZ '2025-04-03T11:23:19.838371Z', 'admin@gmail.com', NULL, TIMESTAMPTZ '2025-04-03T11:23:19.83846Z', 'W/6/+1bJthrexPell8vPZFOcVxXzuZzWsNnZdXUAu0E=', NULL, 3, 1, 'admin');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250403112320_PasswordRecoveryAndEmailConfirmation') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250403112320_PasswordRecoveryAndEmailConfirmation', '9.0.2');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250405182320_ProfilePictureAdd') THEN
    DELETE FROM users
    WHERE id = '3d1813da-ab04-4045-97ed-e43f1c4fd51f';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250405182320_ProfilePictureAdd') THEN
    ALTER TABLE users ADD profile_picture_file_name character varying(300) NOT NULL DEFAULT 'user_default_pfp.png';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250405182320_ProfilePictureAdd') THEN
    INSERT INTO users (id, created_at, email, email_confirmation_token, last_activity, password_hash, password_recovery_token, role_id, status, username)
    VALUES ('af3aa042-cf34-41f8-877a-43c77b9bf83a', TIMESTAMPTZ '2025-04-05T18:23:19.29126Z', 'admin@gmail.com', NULL, TIMESTAMPTZ '2025-04-05T18:23:19.291307Z', 'Ugc4Bt8RYVH6mgiQK/dsOgz2d7exWjiqrVWFZkBEb6A=', NULL, 3, 1, 'admin');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250405182320_ProfilePictureAdd') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250405182320_ProfilePictureAdd', '9.0.2');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250416144757_ProfilePictureIsNullableAndAdminChanges') THEN
    DELETE FROM users
    WHERE id = 'af3aa042-cf34-41f8-877a-43c77b9bf83a';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250416144757_ProfilePictureIsNullableAndAdminChanges') THEN
    ALTER TABLE users ALTER COLUMN profile_picture_file_name DROP NOT NULL;
    ALTER TABLE users ALTER COLUMN profile_picture_file_name DROP DEFAULT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250416144757_ProfilePictureIsNullableAndAdminChanges') THEN
    INSERT INTO users (id, created_at, email, email_confirmation_token, last_activity, password_hash, password_recovery_token, profile_picture_file_name, role_id, status, username)
    VALUES ('df6b1476-c214-4103-90d0-6fae25e74bca', TIMESTAMPTZ '-infinity', 'admin@gmail.com', NULL, TIMESTAMPTZ '-infinity', 'bxHPtLKhH1H2j+eNQCNxzR6hMCXByycYrF/fx3Oo/4Y=', NULL, NULL, 3, 1, 'admin');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250416144757_ProfilePictureIsNullableAndAdminChanges') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250416144757_ProfilePictureIsNullableAndAdminChanges', '9.0.2');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250417181057_UserLastActivityRename') THEN
    ALTER TABLE users RENAME COLUMN last_activity TO last_activity_at;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250417181057_UserLastActivityRename') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250417181057_UserLastActivityRename', '9.0.2');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250420230047_PreviousStatusColumn') THEN
    ALTER TABLE users ADD previous_status integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250420230047_PreviousStatusColumn') THEN
    UPDATE users SET previous_status = NULL
    WHERE id = 'df6b1476-c214-4103-90d0-6fae25e74bca';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250420230047_PreviousStatusColumn') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250420230047_PreviousStatusColumn', '9.0.2');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250510074616_ChatOwnerNullable') THEN
    ALTER TABLE chats ALTER COLUMN owner_id DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250510074616_ChatOwnerNullable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250510074616_ChatOwnerNullable', '9.0.2');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250624051616_ChatPicture') THEN
    ALTER TABLE users ALTER COLUMN username TYPE character varying(30);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250624051616_ChatPicture') THEN
    ALTER TABLE chats ADD chat_picture_file_name character varying(300);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250624051616_ChatPicture') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250624051616_ChatPicture', '9.0.2');
    END IF;
END $EF$;
COMMIT;

